name: Alhany
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  record: ^3.0.0
#  flutter_audio_recorder:
#    git:
#      url: https://github.com/androsoftweb/flutter_audio_recorder
  permission_handler: '^4.2.0+hotfix.3'
  firebase_auth: 1.0.2
  video_player: ^2.1.2
  #better_player: ^0.0.61
  flutter_ffmpeg: ^0.4.0
  fluttertoast: ^8.0.2
  cloud_firestore: 1.0.3
  firebase_storage: ^8.0.1
  firebase_core: ^1.0.3
  shared_preferences: ^2.0.6
  cached_network_image: ^3.0.0
  file_picker: 3.0.0
  #audioplayers: ^0.15.0
  loading: ^1.0.2
  http: ^0.13.1
  random_string: ^2.0.1
  google_sign_in: ^5.0.3
  image_picker: ^0.7.5
  photo_view: ^0.11.0
  firebase_messaging: 9.1.0
  flutter_local_notifications: ^6.0.0
  stripe_payment: ^1.1.0
  #encrypt:
  #aes_crypt: ^0.1.1
  sqflite: ^2.0.0
  html_editor:
    git:
      url: https://github.com/androsoftweb/flutter-html-editor
  path_provider:
  camera: ^0.8.1+1
  #camera_fix_exception: ^0.4.0+5
  badges: ^2.0.1
  audio_service: ^0.17.0
  audio_session: ^0.1.1
  firebase_dynamic_links:
  share: ^2.0.2
  linked_scroll_controller: ^0.2.0
  flutter_widget_from_html_core:
  percent_indicator: ^3.0.1
  flutter_credit_card: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_login_facebook: ^1.0.0
  simple_gesture_detector: ^0.1.4
  apple_sign_in: ^0.1.0
  provider: ^5.0.0
  just_audio: ^0.7.1
  #flutter_imagepress: ^0.7.0
  flutter_webview_plugin:
  screen: ^0.0.5
  pip_view: ^0.9.5
  readmore: ^2.0.0
  ext_storage: ^1.0.3
  firebase_remote_config: ^00.10.0
  chewie: ^1.1.0
  table_calendar: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf

