name: Alhany
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_audio_recorder: ^0.5.5
  #sounds: 1.0.0-beta13
  permission_handler: '^4.2.0+hotfix.3'
  firebase_auth:
  video_player: ^0.10.10
  flutter_ffmpeg: ^0.3.0
  fluttertoast: ^7.1.1
  cloud_firestore:
  firebase_storage: ^7.0.0
  firebase_core: ^0.7.0
  shared_preferences: ^0.5.6+3
  cached_network_image: ^2.0.0
  file_picker: 2.0.0
  audioplayers: ^0.15.0
  loading: ^1.0.2
  http: ^0.12.2
  random_string: ^2.0.1
  google_sign_in: ^4.5.4
  image_picker: ^0.6.7+4
  photo_view: ^0.9.2
  firebase_messaging: 8.0.0-dev.14
  flutter_local_notifications: ^1.1.6
  stripe_payment: ^1.0.9
  encrypt:
  aes_crypt: ^0.1.1
  sqflite: ^1.3.1+1
  html_editor: ^1.0.1
  path_provider: ^1.6.10
  camera: ^0.7.0
  badges: ^1.1.0
  #audio_service: ^0.16.2+1
  audio_session: ^0.0.11
  firebase_dynamic_links:
  share: ^0.6.3+4
  linked_scroll_controller: ^0.1.2
  flutter_widget_from_html_core:
  percent_indicator: ^2.1.8
  flutter_credit_card: ^0.1.4
  carousel_slider: ^2.3.1
  flutter_login_facebook: ^0.4.0+1
  simple_gesture_detector: ^0.1.4
  apple_sign_in: ^0.1.0
  provider: ^4.3.3
  #flutter_imagepress: ^0.7.0
  flutter_webview_plugin:
  screen: ^0.0.5
  #rxdart: ^0.25.0
  #audio_manager: ^0.7.3
  just_audio: ^0.6.13
  flutter_tts: ^0.8.5
  rxdart: "0.25.0"
  audio_service:
  pip_view: ^0.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf

