name: Alhany
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+3

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #  flutter_audio_recorder: ^0.5.5
  #sounds: ^0.9.3
  permission_handler: ^6.1.3
  firebase_auth: ^1.0.2
  video_player: ^2.1.1
  flutter_ffmpeg: ^0.4.0
  fluttertoast: ^8.0.3
  cloud_firestore: ^1.0.4
  firebase_storage: ^8.0.2
  firebase_core: ^1.0.3
  shared_preferences: ^2.0.5
  better_player: ^0.0.61
  cached_network_image: ^3.0.0
  file_picker: ^3.0.1
  audioplayers: ^0.18.3
  loading: ^1.0.2
  http: ^0.13.1
  random_string: ^2.0.1
  google_sign_in: ^5.0.1
  image_picker: ^0.7.4
  photo_view: ^0.9.2
  #audioplayers: ^0.15.0
  firebase_messaging: ^9.1.1
  flutter_local_notifications: ^5.0.0+1
  stripe_payment: ^1.0.9
  encrypt:
  aes_crypt: ^0.1.1
  sqflite: ^2.0.0+3
  #  html_editor: ^1.0.1
  path_provider: ^2.0.1
  camera: ^0.8.1
  #camera_fix_exception: ^0.4.0+5
  badges: ^1.1.0
  audio_session: ^0.1.0
  firebase_dynamic_links: ^0.8.0
  share: ^2.0.1
  linked_scroll_controller: ^0.1.2
  flutter_widget_from_html_core:
  percent_indicator: ^3.0.1
  flutter_credit_card: ^2.0.0
  carousel_slider: ^3.0.0
  flutter_login_facebook: ^1.0.1
  simple_gesture_detector: ^0.2.0
  apple_sign_in: ^0.1.0
  provider: ^5.0.0
  audio_service: ^0.17.0
  just_audio: ^0.7.3
  #flutter_imagepress: ^0.7.0
  flutter_webview_plugin:
  screen: ^0.0.5
  pip_view: ^0.9.5
  readmore: ^2.0.0
  #  audio_recorder:
  #    git:
  #      url: https://github.com/androsoftweb/audio_recorder
  flutter_audio_recorder:
    git:
      url: https://github.com/androsoftweb/flutter_audio_recorder
  html_editor:
    git:
      url: https://github.com/androsoftweb/flutter-html-editor

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf