name: Alhany
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_audio_recorder: ^0.5.5
  permission_handler: '^4.2.0+hotfix.3'
  firebase_auth: ^0.14.0+5
  video_player: ^0.11.0
  flutter_ffmpeg: ^0.3.0
  fluttertoast: ^7.1.1
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.0.6
  shared_preferences: ^0.5.6+3
  cached_network_image: ^2.0.0
  file_picker: ^2.0.0
  audioplayers: ^0.15.0
  loading: ^1.0.2
  http: ^0.12.0+2
  random_string: ^2.0.1
  google_sign_in: ^4.5.4
  image_picker: ^0.6.7+4
  photo_view: ^0.9.2
  firebase_messaging: ^6.0.9
  flutter_local_notifications: ^1.1.6
  stripe_payment: ^1.0.8
  encrypt: ^4.1.0
  aes_crypt: ^0.1.1
  sqflite: ^1.3.1+1
  flutter_summernote: ^0.2.0
  html_editor: ^1.0.1
  path_provider:
  camera: ^0.5.8+11
  badges: ^1.1.0
  audio_service: ^0.15.3
  just_audio: ^0.5.6
  audio_session: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf

